title:              Vikhyat's website
email:              vikhyatagrawal2002@gmail.com 
description:        My personal website
author:             Vikhyat Agrawal
baseurl:            ""
url:                "https://vikhyatagrawal.github.io"

# Social Profiles
twitter_username:   
github_username:    vikhyatagrawal
facebook_username:  Vikhyat Agrawal
instagram_username:  itsvikhyat_
linkedin_username:  Vikhyat Agrawal

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
